# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/LayoutEditor.sln'
  MajorVersion: 1
  MinorVersion: 0
  InitialReleaseTagNumber: 1
  IncrementReleaseTagNumber: $[counter(variables['InitialReleaseTagNumber'], 0)]
  
steps:
- checkout: self
  path: s/RGB.NET-Layout-Editor

- task: DotNetCoreCLI@2
  displayName: 'Publish LayoutEditor'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(solution)'
    arguments: '--runtime win-x64 -p:PublishSingleFile=true --self-contained true --output $(Build.BinariesDirectory) /nowarn:cs1591'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishPipelineArtifact@1
  displayName: 'Upload build to Azure Pipelines'
  inputs:
    targetPath: '$(Build.BinariesDirectory)'
    artifact: 'Editor build'
    publishLocation: 'pipeline'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/rgb-net-layout-editor.zip'
    replaceExistingArchive: true

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_SpoinkyNL'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v$(MajorVersion).$(MinorVersion).$(IncrementReleaseTagNumber)'
    releaseNotesSource: 'inline'
    releaseNotesInline: 'Automated release by Azure Pipelines'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'